backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - label: "Page Content"
            name: "body"
            widget: "markdown"

      - label: "About Page"
        name: "about"
        file: "pages/about.html"
        fields:
          - label: "Page Content"
            name: "body"
            widget: "markdown"
